services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    build:
      context: "."
      dockerfile: "Dockerfile_jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deploy-network

networks:
  deploy-network:
    name: deploy-network
    driver: bridge
