services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      deploy-network:
        ipv4_address: 172.32.0.2 # Assign a static IP to Jenkins

networks:
  deploy-network:
    name: deploy-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16
