pipeline {
    agent any

    tools {
        nodejs 'NODEJS_23'
        terraform 'TF_DEFAULT'
    }

    environment {
        GITHUB_REPO = 'https://github.com/marci0929/devops_project.git'
        BRANCH = 'master'
        DEPLOY_CONTAINER = 'stickers-app'
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'mkdir -p app'
                sh 'cd app'
                sh 'rm -rf *'
                git branch: env.BRANCH, url: env.GITHUB_REPO
            }
        }

        stage('Test build'){
            steps {
                sh 'npm install -g @angular/cli'
                sh 'npm install'
                sh 'ng build'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Refreshing the application...'
                dir('terraform-project') {
                    sh 'terraform init -no-color'
                    sh 'test -z $(docker ps --filter name=stickers-app -q) || docker stop $(docker ps --filter name=stickers-app -q)'
                    sh 'terraform apply -auto-approve -no-color'
                }
            }
        }
    }


    post {
        success {
            echo 'Application is running!'
        }
        failure {
            echo 'Errors happened during deployment!'
        }
    }
}