global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'stickers-app'
    scrape_interval: 5s
    static_configs:
      - targets:
        - '172.48.0.20:4200'
        - '172.48.0.21:4200'
        - '172.48.0.22:4200'
        - '172.48.0.23:4200'