services:
  bind9:
    build:
      context: .
      dockerfile: Dockerfile_bind9
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
    volumes:
      - ./bind_config:/etc/bind
    networks:
      - app_network
    cap_add:
      - NET_ADMIN

networks:
  app_network:
    driver: bridge
