# Build stage
FROM node:23-alpine
RUN apk update
RUN apk add git
RUN apk add curl

WORKDIR /app
RUN git clone https://github.com/marci0929/devops_project.git
WORKDIR /app/devops_project

RUN git checkout master
RUN npm install -g @angular/cli
RUN npm install
RUN ng build
RUN ng analytics off

# Install Zabbix Agent
RUN apk add --no-cache \
    pcre \
    zabbix-agent2
# Configure Zabbix Agent
COPY zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf

RUN mkdir -p /var/log/pm2

# Configure PM2 to use syslog
ENV PM2_SYSLOG=true

EXPOSE 4200 10050

CMD ["ng", "serve", "--host", "0.0.0.0"]