# Build stage
FROM node:23-alpine
RUN apk update
RUN apk add git
RUN apk add curl

WORKDIR /app
RUN git clone https://github.com/marci0929/devops_project.git
WORKDIR /app/devops_project

RUN git checkout master
RUN npm install -g @angular/cli
RUN npm install
RUN ng build
RUN ng analytics off

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]